language: java

jdk: openjdk8

cache:
  directories:
    - "$HOME/.m2/repository"

script:
  - mvn clean package

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 27bb395b-6dd6-4e34-9f67-ba129f13da3a
